US2_2T1 Implement API for admin to get all and get one transaction
FaiiFaiipuipui/CEDT_Y1T2_backend-campgroundbooking pull request #12
Opened 2024-04-12 13:18 UTC by ShamaW

- Add Transaction controllers 
- Add function to get one transaction and get all the transactions

2024-04-12 18:58 UTC, Yiwahpsp reviewed
Have 2 comments please take a look, other looks great

2024-04-13 06:00 UTC, FaiiFaiipuipui commented on controllers/transactions.js
> +
resolved yet?

2024-04-13 06:00 UTC, FaiiFaiipuipui commented on controllers/transactions.js
> +      })
resolved yet?

2024-04-13 06:59 UTC, FaiiFaiipuipui requested changes

2024-04-13 06:59 UTC, FaiiFaiipuipui commented on controllers/transactions.js
are there any way for admin/user to get their transaction slip?

2024-04-13 06:59 UTC, FaiiFaiipuipui commented on controllers/transactions.js
> +  if (req.user.role !== "admin") {
from routes/transactions.js only the admins are allowed to access this API. are user able to access this API too?

2024-04-13 08:00 UTC, ShamaW commented
Try to make some change according to you guy's suggestion. How does it look?

2024-04-13 18:45 UTC, Yiwahpsp approved these changes
look great!!

2024-04-14 05:13 UTC, BoondaPanich approved these changes
lgtm

2024-04-14 07:08 UTC, BoondaPanich approved these changes
Looks good kub 👍👍

2024-04-14 09:08 UTC, FaiiFaiipuipui approved these changes
Please review comment and then I think it's all good😺👍

2024-04-14 09:08 UTC, FaiiFaiipuipui commented on routes/campgrounds.js
> +router.use('/:campgroundId/transactions/', transactionRouter);
Is this route suppose to exist?

2024-04-14 09:23 UTC, Yiwahpsp approved these changes
look goodddd

2024-04-14 10:26 UTC, merged