feat: add transaction via post method
FaiiFaiipuipui/CEDT_Y1T2_backend-campgroundbooking pull request #9
Opened 2024-04-12 08:47 UTC by pccherrii

- create controllers/transactions.js file
- create routes/transactions.js file
- edit routes/appointment.js: for nested routes
- edit server.js: add transactions router

2024-04-12 09:03 UTC, Yiwahpsp approved these changes
Looks Good

2024-04-12 09:14 UTC, tippaphanun approved these changes
👍🏻

2024-04-12 09:51 UTC, ShamaW reviewed
in controllers/transactions.js change according the @FaiiFaiipuipui suggestion

2024-04-12 17:48 UTC, tippaphanun approved these changes

2024-04-12 18:44 UTC, Yiwahpsp reviewed
everything looks good

2024-04-12 18:44 UTC, Yiwahpsp commented on controllers/transactions.js
> +
Check campground maybe safe more

2024-04-12 18:48 UTC, Yiwahpsp reviewed
please answer my 2 comments, other looks great

2024-04-12 18:48 UTC, Yiwahpsp commented on routes/transactions.js
Have you create router for /transaction/:appiontmentId

2024-04-13 06:14 UTC, FaiiFaiipuipui requested changes, later dismissed

2024-04-13 06:14 UTC, FaiiFaiipuipui commented on controllers/transactions.js
> +    const transaction = await Transaction.create(req.body);
I'm a bit confused as just creating new document in Transaction from req.body is not enough.

from the database schema the planned way of creating and updating a transaction document might look like this
1. get slip_image from req.body
2. insert slip_image into transactionSlip
3. insert various information (including ObjectId of the newly inserted slip_image doucment) into transaction where applicable

Thx.

2024-04-13 06:22 UTC, FaiiFaiipuipui commented on routes/transactions.js
seem so

2024-04-15 15:45 UTC, ShamaW approved these changes

2024-04-16 11:41 UTC, merged